/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;
import Data.CategoriaData;
import jFrame.Gestion;
import laboratorio.practica6.Producto;
import java.util.TreeSet;
import laboratorio.practica6.Categoria;

/**
 *
 * @author Tomas
 */
public class MenuPrincipal extends javax.swing.JFrame {
public static TreeSet<Producto> listaProductos =new TreeSet<>(); 
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuProduct1 = new javax.swing.JMenuItem();
        jMenuCunsultas = new javax.swing.JMenu();
        jMenuxRubro2 = new javax.swing.JMenuItem();
        jMenuxNom3 = new javax.swing.JMenuItem();
        jMenuxPrec4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JEscritorioLayout = new javax.swing.GroupLayout(JEscritorio);
        JEscritorio.setLayout(JEscritorioLayout);
        JEscritorioLayout.setHorizontalGroup(
            JEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        JEscritorioLayout.setVerticalGroup(
            JEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        jMenuAdmin.setText("Administracion ");

        jMenuProduct1.setText("Productos");
        jMenuProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProduct1ActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuProduct1);

        jMenuBar1.add(jMenuAdmin);

        jMenuCunsultas.setText("Consultas");
        jMenuCunsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCunsultasActionPerformed(evt);
            }
        });

        jMenuxRubro2.setText("Por rubro");
        jMenuxRubro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuxRubro2ActionPerformed(evt);
            }
        });
        jMenuCunsultas.add(jMenuxRubro2);

        jMenuxNom3.setText("Por nombre");
        jMenuxNom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuxNom3ActionPerformed(evt);
            }
        });
        jMenuCunsultas.add(jMenuxNom3);

        jMenuxPrec4.setText("Por precio");
        jMenuxPrec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuxPrec4ActionPerformed(evt);
            }
        });
        jMenuCunsultas.add(jMenuxPrec4);

        jMenuBar1.add(jMenuCunsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProduct1ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       Gestion gp= new Gestion();
       gp.setVisible(true);
       JEscritorio.add(gp);
       JEscritorio.moveToFront(gp);
    }//GEN-LAST:event_jMenuProduct1ActionPerformed

    private void jMenuxNom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuxNom3ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       BusquedaPorNombre bpn= new BusquedaPorNombre();
       bpn.setVisible(true);
       JEscritorio.add(bpn);
       JEscritorio.moveToFront(bpn);
    }//GEN-LAST:event_jMenuxNom3ActionPerformed

    private void jMenuxRubro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuxRubro2ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       BusquedaPorRubro bpr= new BusquedaPorRubro();
       bpr.setVisible(true);
       JEscritorio.add(bpr);
       JEscritorio.moveToFront(bpr);
    }//GEN-LAST:event_jMenuxRubro2ActionPerformed

    private void jMenuCunsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCunsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCunsultasActionPerformed

    private void jMenuxPrec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuxPrec4ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       BusquedaPorPrecio bpp= new BusquedaPorPrecio();
       bpp.setVisible(true);
       JEscritorio.add(bpp);
       JEscritorio.moveToFront(bpp);
    }//GEN-LAST:event_jMenuxPrec4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JEscritorio;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCunsultas;
    private javax.swing.JMenuItem jMenuProduct1;
    private javax.swing.JMenuItem jMenuxNom3;
    private javax.swing.JMenuItem jMenuxPrec4;
    private javax.swing.JMenuItem jMenuxRubro2;
    // End of variables declaration//GEN-END:variables

    public void cargarProductos(){
        listaProductos.add(new Producto(189,"Azucar 1kg", 34, 725.6,  almacen));
        listaProductos.add(new Producto(456,"LECHE 1L", 54, 5967.6, fiambres));
        listaProductos.add(new Producto(4875,"tupper 500ml", 98, 2984.6, bazar));
        listaProductos.add(new Producto(237,"desodorante rexona", 75, 984.6, perfumeria));
        listaProductos.add(new Producto(567,"lavandina 1L", 32, 1984.6, limpieza));
    }
    Categoria fiambres= new Categoria( 1,"Fiambres");
    Categoria lacteos=new Categoria(2, "Lacteos");
    Categoria almacen=new Categoria(3, "Almacen");
    Categoria perfumeria=new Categoria(4, "Perfumeria");
    Categoria bazar=new Categoria(5, "Bazar");
    Categoria limpieza=new Categoria(6, "Limpieza");
 
   
    
    


}
