/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;
import clases.Producto;
import java.util.TreeSet;

/**
 *
 * @author Roma
 */
public class MenuPrincipal extends javax.swing.JFrame {
public static TreeSet<Producto> listaProductos = new TreeSet<>(); 
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuProduct1 = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuxRubro2 = new javax.swing.JMenuItem();
        jMenuxNom3 = new javax.swing.JMenuItem();
        jMenuxPrec4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JEscritorioLayout = new javax.swing.GroupLayout(JEscritorio);
        JEscritorio.setLayout(JEscritorioLayout);
        JEscritorioLayout.setHorizontalGroup(
            JEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        JEscritorioLayout.setVerticalGroup(
            JEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        jMenuAdmin.setText("Administracion ");

        jMenuProduct1.setText("Productos");
        jMenuProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProduct1ActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuProduct1);

        jMenuBar1.add(jMenuAdmin);

        jMenuConsultas.setText("Consultas");
        jMenuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultasActionPerformed(evt);
            }
        });

        jMenuxRubro2.setText("Por rubro");
        jMenuxRubro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuxRubro2ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuxRubro2);

        jMenuxNom3.setText("Por nombre");
        jMenuxNom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuxNom3ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuxNom3);

        jMenuxPrec4.setText("Por precio");
        jMenuxPrec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuxPrec4ActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuxPrec4);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProduct1ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       Gestion gp= new Gestion();
       gp.setVisible(true);
       JEscritorio.add(gp);
       JEscritorio.moveToFront(gp);
    }//GEN-LAST:event_jMenuProduct1ActionPerformed

    private void jMenuxNom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuxNom3ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       BusquedaPorNombre bpn= new BusquedaPorNombre();
       bpn.setVisible(true);
       JEscritorio.add(bpn);
       JEscritorio.moveToFront(bpn);
    }//GEN-LAST:event_jMenuxNom3ActionPerformed

    private void jMenuxRubro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuxRubro2ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       BusquedaPorRubro bpr= new BusquedaPorRubro();
       bpr.setVisible(true);
       JEscritorio.add(bpr);
       JEscritorio.moveToFront(bpr);
    }//GEN-LAST:event_jMenuxRubro2ActionPerformed

    private void jMenuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuConsultasActionPerformed

    private void jMenuxPrec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuxPrec4ActionPerformed
       JEscritorio.removeAll();
       JEscritorio.repaint();
       BusquedaPorPrecio bpp= new BusquedaPorPrecio();
       bpp.setVisible(true);
       JEscritorio.add(bpp);
       JEscritorio.moveToFront(bpp);
    }//GEN-LAST:event_jMenuxPrec4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JEscritorio;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuProduct1;
    private javax.swing.JMenuItem jMenuxNom3;
    private javax.swing.JMenuItem jMenuxPrec4;
    private javax.swing.JMenuItem jMenuxRubro2;
    // End of variables declaration//GEN-END:variables

    public void cargarProductos(){
        listaProductos.add(new Producto(189, "Azucar 1kg", 725.6, "Comestible", 34));
        listaProductos.add(new Producto(456, "Leche 1L", 5967, "Comestible", 54));
        listaProductos.add(new Producto(200, "Desodorante rexona", 984.6, "Perfumeria", 75));
        listaProductos.add(new Producto(890, "Jabón en polvo 800g", 432.5, "Limpieza", 27));
        listaProductos.add(new Producto(567, "Lavandina 1L", 1984.6, "Limpieza", 32));
        listaProductos.add(new Producto(789, "Detergente 500ml", 299.9, "Limpieza", 40));
        listaProductos.add(new Producto(234, "Escoba", 785.3, "Limpieza", 15));
        listaProductos.add(new Producto(901, "Harina 1kg", 180.3, "Comestible", 50));
        listaProductos.add(new Producto(112, "Arroz 1kg", 250.7, "Comestible", 45));
        listaProductos.add(new Producto(345, "Shampoo 500ml", 1025.5, "Perfumeria", 20));
        listaProductos.add(new Producto(678, "Crema corporal 200ml", 1540.8, "Perfumeria", 10));
    }
 
   
    

}
